### ISSUE TITLE
make it conda installable

### ISSUE THREAD

**Issue by RNAer** [biocore/micronota#3]
It will includes external softwares too. And we are trying to make the pipeline work in Windows system as well (thanks to @ElDeveloper 's suggestion).

Let's try include prodigal (https://github.com/hyattpd/Prodigal/releases), infernal (http://infernal.janelia.org/) and hmmer3 (http://hmmer.janelia.org/) at first in conda installation recipe.

**Comment by Jorge-C** [comment]
Hey @RNAer! Since you mentioned this was blocking I've been working on it and have preliminary results on linux-64, where you should be able to install the three deps using:
```
conda install -c https://conda.anaconda.org/jorge hmmer prodigal inferno
```
Let me know if that works well! 

I think the same recipes should work in OSX, but work is necessary in the Windows front. I don't have easy access to that OS but will try a bunch of things.

Would you like the recipes in this repo? I can make a PR.

**Comment by RNAer** [comment]
Thanks, Jorge! Just test it on barnacle. I can install it, but when running
it, there is a problem:

$ prodigal
prodigal: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by
prodigal)

This is the same for hmmer and infernal.

**Comment by RNAer** [comment]
And it doesn't work on OSX:

$ conda install -c https://conda.anaconda.org/jorge infernal
Fetching package metadata: ......
Error: No packages found in current osx-64 channels matching: infernal

You can search for this package on anaconda.org with

    anaconda search -t conda infernal

**Comment by ElDeveloper** [comment]
@RNAer, it's not gonna work on OSX as is, we need to use the recipies to re-build the binaries and then it should work on OS X.

I have a couple windows VMs, but I haven't done any development on those for a while (4+ years), though I'm down to help getting those.

**Comment by Jorge-C** [comment]
@ElDeveloper is right about the OSX rebuild.

The barnacle error is well known (binaries compiled against old glibc will work with newer ones, but not the other way around). I've re-compiled (against glibc 2.12) and re-uploaded, would you mind trying again in Barnacle (it seems to work in pando)?

Do we want a biocore-recipes repo, or keeping them here would be fine?

**Comment by RNAer** [comment]
@Jorge-C , it is working. I thought you were packaging the binary exe in the recipe, which may avoid this type of library dep problems?

As on recipes, I think biocore/conda-recipes is the way to go, make the recipes for widely used tools and put them in a centralized repo. what do you guys think? @ElDeveloper @gregcaporaso @antgonza @mortonjt @wasade

**Comment by ElDeveloper** [comment]
This makes sense, then maybe that can be absorbed by a larger repository
of recipes focused on bioinformatics resources.

**Comment by Jorge-C** [comment]
@RNAer great! Precompiled binaries (what you download when calling `conda install ...`) will work as long as the underlying system is "compatible enough". In practice, this means that we need to compile the code (build the binaries) in an old system, so that they work in any newer system. Does that make sense?

**Comment by RNAer** [comment]
@Jorge-C , oh I see, the library was not statically linked into the exe. Perhaps we should do that in case users miss any dependency?

Created conda-recipes (https://github.com/biocore/conda-recipes). could you put your recipes there? and perhaps create a channel of biocre on anaconda?

**Comment by Jorge-C** [comment]
Nope, but that's due to their build process, and is unrelated to conda. We could patch their build process to statically link every library they use. A drawback (on top of binary size, being not unix-y) is that we'd have to maintain yet another piece any time their build process changes...
It's much easier to rely on glibc's backward compatibility, and just build the binaries in any of our servers (as opposed to in a system using eg ubuntu 15.XX and a recent glibc).

**Comment by ElDeveloper** [comment]
:+1:, let's leave this to the conda maintainers and instead just find a
machine with an compatible (read old) set of common libraries.

**Comment by RNAer** [comment]
makes sense.

**Comment by Jorge-C** [comment]
Cool, PR issued.

**Comment by RNAer** [comment]
:+1: aweseome
